"""create meeting workspace schema

Revision ID: da26b8757ff7
Revises:
Create Date: 2026-08-14 00:13:26.180022

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da26b8757ff7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Account",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("displayName", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("avatarUrl", sa.String(length=500), nullable=True),
        sa.Column("createdAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Account")),
    )
    op.create_index(op.f("idx_Account_email"), "Account", ["email"], unique=True)
    op.create_table(
        "Participant",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatarColor", sa.String(length=20), nullable=False),
        sa.Column("createdAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Participant")),
    )
    op.create_index(op.f("idx_Participant_email"), "Participant", ["email"], unique=False)
    op.create_index(op.f("idx_Participant_name"), "Participant", ["name"], unique=False)
    op.create_table(
        "Meeting",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ownerAccountId", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("meetingAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("durationInSeconds", sa.Integer(), nullable=False),
        sa.Column("sourceType", sa.String(length=30), nullable=False),
        sa.Column("mediaUrl", sa.String(length=500), nullable=True),
        sa.Column("deletedAtUtc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("createdAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "durationInSeconds >= 0", name=op.f("ck_Meeting_meeting_duration_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["ownerAccountId"], ["Account.id"], name=op.f("fk_Meeting_ownerAccountId_Account")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Meeting")),
    )
    op.create_index(op.f("idx_Meeting_deletedAtUtc"), "Meeting", ["deletedAtUtc"], unique=False)
    op.create_index(op.f("idx_Meeting_meetingAtUtc"), "Meeting", ["meetingAtUtc"], unique=False)
    op.create_index(op.f("idx_Meeting_ownerAccountId"), "Meeting", ["ownerAccountId"], unique=False)
    op.create_index(op.f("idx_Meeting_title"), "Meeting", ["title"], unique=False)
    op.create_table(
        "ActionItem",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("meetingId", sa.String(length=36), nullable=False),
        sa.Column("assigneeParticipantId", sa.String(length=36), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("isCompleted", sa.Boolean(), nullable=False),
        sa.Column("dueAtUtc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("createdAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigneeParticipantId"],
            ["Participant.id"],
            name=op.f("fk_ActionItem_assigneeParticipantId_Participant"),
        ),
        sa.ForeignKeyConstraint(
            ["meetingId"],
            ["Meeting.id"],
            name=op.f("fk_ActionItem_meetingId_Meeting"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ActionItem")),
    )
    op.create_index(
        op.f("idx_ActionItem_assigneeParticipantId"),
        "ActionItem",
        ["assigneeParticipantId"],
        unique=False,
    )
    op.create_index(op.f("idx_ActionItem_isCompleted"), "ActionItem", ["isCompleted"], unique=False)
    op.create_index(op.f("idx_ActionItem_meetingId"), "ActionItem", ["meetingId"], unique=False)
    op.create_table(
        "Chapter",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("meetingId", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("startInSeconds", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "startInSeconds >= 0", name=op.f("ck_Chapter_chapter_start_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["meetingId"],
            ["Meeting.id"],
            name=op.f("fk_Chapter_meetingId_Meeting"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Chapter")),
    )
    op.create_index(op.f("idx_Chapter_meetingId"), "Chapter", ["meetingId"], unique=False)
    op.create_table(
        "MeetingParticipant",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("meetingId", sa.String(length=36), nullable=False),
        sa.Column("participantId", sa.String(length=36), nullable=False),
        sa.Column("isHost", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meetingId"],
            ["Meeting.id"],
            name=op.f("fk_MeetingParticipant_meetingId_Meeting"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["participantId"],
            ["Participant.id"],
            name=op.f("fk_MeetingParticipant_participantId_Participant"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_MeetingParticipant")),
        sa.UniqueConstraint(
            "meetingId", "participantId", name=op.f("uq_MeetingParticipant_meetingId")
        ),
    )
    op.create_index(
        op.f("idx_MeetingParticipant_meetingId"), "MeetingParticipant", ["meetingId"], unique=False
    )
    op.create_index(
        op.f("idx_MeetingParticipant_participantId"),
        "MeetingParticipant",
        ["participantId"],
        unique=False,
    )
    op.create_table(
        "MeetingSummary",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("meetingId", sa.String(length=36), nullable=False),
        sa.Column("overview", sa.Text(), nullable=False),
        sa.Column("createdAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["meetingId"],
            ["Meeting.id"],
            name=op.f("fk_MeetingSummary_meetingId_Meeting"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_MeetingSummary")),
    )
    op.create_index(
        op.f("idx_MeetingSummary_meetingId"), "MeetingSummary", ["meetingId"], unique=True
    )
    op.create_table(
        "TranscriptSegment",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("meetingId", sa.String(length=36), nullable=False),
        sa.Column("speakerParticipantId", sa.String(length=36), nullable=True),
        sa.Column("sequenceNumber", sa.Integer(), nullable=False),
        sa.Column("startInSeconds", sa.Float(), nullable=False),
        sa.Column("endInSeconds", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("createdAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updatedAtUtc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "endInSeconds >= startInSeconds",
            name=op.f("ck_TranscriptSegment_segment_end_after_start"),
        ),
        sa.CheckConstraint(
            "startInSeconds >= 0", name=op.f("ck_TranscriptSegment_segment_start_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["meetingId"],
            ["Meeting.id"],
            name=op.f("fk_TranscriptSegment_meetingId_Meeting"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["speakerParticipantId"],
            ["Participant.id"],
            name=op.f("fk_TranscriptSegment_speakerParticipantId_Participant"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TranscriptSegment")),
        sa.UniqueConstraint(
            "meetingId", "sequenceNumber", name=op.f("uq_TranscriptSegment_meetingId")
        ),
    )
    op.create_index(
        op.f("idx_TranscriptSegment_meetingId"), "TranscriptSegment", ["meetingId"], unique=False
    )
    op.create_index(
        op.f("idx_TranscriptSegment_speakerParticipantId"),
        "TranscriptSegment",
        ["speakerParticipantId"],
        unique=False,
    )
    op.create_table(
        "SummaryKeyPoint",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("summaryId", sa.String(length=36), nullable=False),
        sa.Column("sequenceNumber", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["summaryId"],
            ["MeetingSummary.id"],
            name=op.f("fk_SummaryKeyPoint_summaryId_MeetingSummary"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_SummaryKeyPoint")),
        sa.UniqueConstraint(
            "summaryId", "sequenceNumber", name=op.f("uq_SummaryKeyPoint_summaryId")
        ),
    )
    op.create_index(
        op.f("idx_SummaryKeyPoint_summaryId"), "SummaryKeyPoint", ["summaryId"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_SummaryKeyPoint_summaryId"), table_name="SummaryKeyPoint")
    op.drop_table("SummaryKeyPoint")
    op.drop_index(
        op.f("idx_TranscriptSegment_speakerParticipantId"), table_name="TranscriptSegment"
    )
    op.drop_index(op.f("idx_TranscriptSegment_meetingId"), table_name="TranscriptSegment")
    op.drop_table("TranscriptSegment")
    op.drop_index(op.f("idx_MeetingSummary_meetingId"), table_name="MeetingSummary")
    op.drop_table("MeetingSummary")
    op.drop_index(op.f("idx_MeetingParticipant_participantId"), table_name="MeetingParticipant")
    op.drop_index(op.f("idx_MeetingParticipant_meetingId"), table_name="MeetingParticipant")
    op.drop_table("MeetingParticipant")
    op.drop_index(op.f("idx_Chapter_meetingId"), table_name="Chapter")
    op.drop_table("Chapter")
    op.drop_index(op.f("idx_ActionItem_meetingId"), table_name="ActionItem")
    op.drop_index(op.f("idx_ActionItem_isCompleted"), table_name="ActionItem")
    op.drop_index(op.f("idx_ActionItem_assigneeParticipantId"), table_name="ActionItem")
    op.drop_table("ActionItem")
    op.drop_index(op.f("idx_Meeting_title"), table_name="Meeting")
    op.drop_index(op.f("idx_Meeting_ownerAccountId"), table_name="Meeting")
    op.drop_index(op.f("idx_Meeting_meetingAtUtc"), table_name="Meeting")
    op.drop_index(op.f("idx_Meeting_deletedAtUtc"), table_name="Meeting")
    op.drop_table("Meeting")
    op.drop_index(op.f("idx_Participant_name"), table_name="Participant")
    op.drop_index(op.f("idx_Participant_email"), table_name="Participant")
    op.drop_table("Participant")
    op.drop_index(op.f("idx_Account_email"), table_name="Account")
    op.drop_table("Account")
    # ### end Alembic commands ###
